language: php

php:
  - 7.2

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer self-update && composer --version
  - composer install --prefer-source --no-interaction

script:
  - composer test